### ISSUE TITLE
Sponsor logos

### ISSUE THREAD

**Issue by newb-dev-1008** [FACE-Amrita-Bengaluru/SLAC-2020#10]
Past sponsor logos need to be updated; DM Yash for the list of sponsors whose logos should be included. Logos will be provided by Yash too.

**Comment by sathian-icd** [comment]
I would like to work on it. Can you assign it to me?

**Comment by newb-dev-1008** [comment]
@sathian-icd you've been assigned. Go ahead, and send a PR once you've finished.
