### ISSUE TITLE
Change in contact details

### ISSUE THREAD

**Issue by newb-dev-1008** [FACE-Amrita-Bengaluru/SLAC-2020#11]
Update the contact details at the bottom of all the pages. 

**New contact details:**

Email: slacfest2020@gmail.com

Yash Umale, +91-96203 94487
Ch Sri Sai Madhuri, +91-89717 52586
Ritwik Lal, +91-96113 20873

**Comment by LavanyaSirisha** [comment]
Please make me an assignee for this issue #11.

**Comment by newb-dev-1008** [comment]
> Please make me an assignee for this issue #11.

Done, send a PR once you're finished.
