### ISSUE TITLE
Change in number of past editions

### ISSUE THREAD

**Issue by newb-dev-1008** [FACE-Amrita-Bengaluru/SLAC-2020#12]
Under "SLAC in a nutshell", the number of past editions needs to be changed from 8 to 9.

**Comment by AvinashSubhash** [comment]
Hey, I would like to work on it, Can you please assign me?

**Comment by newb-dev-1008** [comment]
> Hey, I would like to work on it, Can you please assign me?

Done, you can start working. Send a PR once you're done with your part.
