### ISSUE TITLE
Remove unnecessary redirection to "Coming Soon" page

### ISSUE THREAD

**Issue by newb-dev-1008** [FACE-Amrita-Bengaluru/SLAC-2020#14]
"Home", "About" and the other buttons on the top bar of the webpage all redirect to the "Coming Soon" website (the one with the countdown). I'd suggest linking the buttons to different relevant parts of the same page.

**Comment by AdithyaSuresh1501** [comment]
Hey there,
I am ready to work on this issue,
Could you please assign it to me.

**Comment by newb-dev-1008** [comment]
@adithyaRocks cool, you've been assigned. Send a pull request once you're done.

**Comment by aravindvnair99** [comment]
@adithyaRocks This is a back-end change. Just a redirection needs to be removed. I'll do it.
