### ISSUE TITLE
Changing 2019 to 2020

### ISSUE THREAD

**Issue by newb-dev-1008** [FACE-Amrita-Bengaluru/SLAC-2020#16]
All mentions of "2019" in the code of conduct and privacy policy need to be changed to "2020".

**Comment by rohitraju1966** [comment]
i'll be doing this one(Rohit.R)

**Comment by newb-dev-1008** [comment]
Cool, you've been assigned

**Comment by aravindvnair99** [comment]
> i'll be doing this one(Rohit.R)

@rohitraju1966 Sure, go ahead. You can send in a PR to fix this issue.

**Comment by rohitraju1966** [comment]
i have a doubt!
how do i run ejs files to check the site?

**Comment by rohitraju1966** [comment]
do i need node js?

**Comment by rohitraju1966** [comment]
<img width="470" alt="Untitled" src="https://user-images.githubusercontent.com/55869757/95452872-8e71f500-0987-11eb-9eb5-dbccaa3a8cfe.png">
can u help me with this error?

**Comment by rohitraju1966** [comment]
am not able to push

**Comment by rohitraju1966** [comment]
PR has been sent
