### ISSUE TITLE
Change the themes

### ISSUE THREAD

**Issue by newb-dev-1008** [FACE-Amrita-Bengaluru/SLAC-2020#4]
Replace "The Theme" with "Tracks".

Tracks:
1. Crisis Response
2. Fintech
3. Healthcare
4. Cyber Security
5. Open Innovation

https://drive.google.com/drive/folders/1NX47QDPhYHkUhENXMM1WKnBTwPKDBfwx?usp=sharing

This folder contains all the required pictures for each track.

**Comment by aravindvnair99** [comment]
@newb-dev-1008 Upload the icons here itself. It's easier to get started that way without delays.

**Comment by newb-dev-1008** [comment]
> @newb-dev-1008 Upload the icons here itself. It's easier to get started that way without delays.

Okay, sure

**Comment by newb-dev-1008** [comment]
![Crisis Response - 1](https://user-images.githubusercontent.com/46532962/95459684-9f276880-0991-11eb-8bb9-12ece0844162.jpg)
![Crisis Response - 2](https://user-images.githubusercontent.com/46532962/95459688-a0589580-0991-11eb-94d7-d9a65a033190.jpg)
![Cybersecurity - 1](https://user-images.githubusercontent.com/46532962/95459689-a0f12c00-0991-11eb-9ece-51a17efc44ef.jpg)
![Cybersecurity - 2](https://user-images.githubusercontent.com/46532962/95459691-a0f12c00-0991-11eb-9c3e-e318e484d591.jpg)
![Fintech - 1](https://user-images.githubusercontent.com/46532962/95459693-a189c280-0991-11eb-9300-2ebd4a128459.jpg)
![Fintech - 2](https://user-images.githubusercontent.com/46532962/95459696-a2225900-0991-11eb-981c-f58a65fca3f3.jpg)
![Healthcare - 1](https://user-images.githubusercontent.com/46532962/95459698-a2225900-0991-11eb-84bc-f343f3db4af7.jpg)
![Healthcare - 2](https://user-images.githubusercontent.com/46532962/95459700-a2baef80-0991-11eb-83ad-cd98239380ba.jpg)
![Open Innovation - 1](https://user-images.githubusercontent.com/46532962/95459703-a3538600-0991-11eb-8a1e-3c26cfa1c57a.jpg)
![Open Innovation - 2](https://user-images.githubusercontent.com/46532962/95459708-a3ec1c80-0991-11eb-8a29-fba5a7beff68.jpg)


These are all the files you'll need for the themes.

**Comment by newb-dev-1008** [comment]
https://drive.google.com/drive/folders/1NX47QDPhYHkUhENXMM1WKnBTwPKDBfwx?usp=sharing

This folder contains all the required pictures for each track.
Please note that the URL given in this comment and the description of the issue are the same.

**Comment by Subaharish** [comment]
I'll take is work.

**Comment by newb-dev-1008** [comment]
@Subaharish you've been assigned. Send a PR once you've finished.
