### ISSUE TITLE
Pricing changes

### ISSUE THREAD

**Issue by newb-dev-1008** [FACE-Amrita-Bengaluru/SLAC-2020#7]
There is no early bird pricing; tickets sell at Rs. 50 flat so there will be only one category instead of two that're currently present.

**Comment by Gandheesh-SA** [comment]
Hell, I would like to work on this issue. Thank you

**Comment by Gandheesh-SA** [comment]
Hello, I would like to work on this issue. Thank you.

**Comment by aravindvnair99** [comment]
> Hello, I would like to work on this issue. Thank you.

@Gandheesh-SA Sure, go ahead. You can send in a PR to fix this issue.

**Comment by Gandheesh-SA** [comment]
Hello Aravind, it say's it can't  automatically merge but can still  create a PR. Do I go with creating a pr?

**Comment by newb-dev-1008** [comment]
@Gandheesh-SA nah bro, you've already created a PR. Aravind will be checking the changes and then merging the PR.
