### ISSUE TITLE
Change of dates

### ISSUE THREAD

**Issue by newb-dev-1008** [FACE-Amrita-Bengaluru/SLAC-2020#9]
Dates mentioned anywhere in the website pertaining to the hackathon need to be changed. 
The new dates are 7th October (10am) - 8th October.

**Comment by Subaharish** [comment]
I'll take this work

**Comment by newb-dev-1008** [comment]
@Subaharish cool, you've been assigned. Send a PR once done.

**Comment by aravindvnair99** [comment]
> Dates mentioned anywhere in the website pertaining to the hackathon need to be changed.
> The new dates are 7th October (10am) - 8th October.

@newb-dev-1008 Isn't it supposed to be November?

**Comment by newb-dev-1008** [comment]
> > Dates mentioned anywhere in the website pertaining to the hackathon need to be changed.
> > The new dates are 7th October (10am) - 8th October.
> 
> @newb-dev-1008 Isn't it supposed to be November?

Ah yes, my bad. Not going to edit that comment, so as to avoid confusion for anyone revisiting these comments; I'll put it up here:

**New dates:** 7th November - 8th November, 10am.
